In [2]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv('/content/Sarcasm Dataset.csv')

In [4]:
dataset.head()

Unnamed: 0                                              tweet  sarcastic  \
0           0  The only thing I got from college is a caffein...          1   
1           1  I love it when professors draw a big question ...          1   
2           2  Remember the hundred emails from companies whe...          1   
3           3  Today my pop-pop told me I was not “forced” to...          1   
4           4  @VolphanCarol @littlewhitty @mysticalmanatee I...          1   

   sarcasm  irony  satire  understatement  overstatement  rhetorical_question  
0      0.0    1.0     0.0             0.0            0.0                  0.0  
1      1.0    0.0     0.0             0.0            0.0                  0.0  
2      0.0    1.0     0.0             0.0            0.0                  0.0  
3      1.0    0.0     0.0             0.0            0.0                  0.0  
4      1.0    0.0     0.0             0.0            0.0                  0.0

In [5]:
dataset.shape

(3468, 9)

In [6]:
import re
import nltk

nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [7]:
corpus=[]

for i in range(0,3468):
  review = re.sub('^[a-zA-Z]',' ',str(dataset['tweet'][i]))
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in all_stopwords]
  review = ' '.join(review)
  corpus.append(review)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()


In [9]:
x = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:,2].values

In [10]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)

In [11]:
from sklearn import svm

classifier = svm.SVC(kernel = 'rbf')
classifier.fit(x_train,y_train)

SVC()

In [12]:
y_pred = classifier.predict(x_test)

print(y_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm = confusion_matrix(y_test,y_pred)
print(cm)

accuracy_score(y_test,y_pred)

[[522   0]
 [171   1]]


0.7536023054755043

In [14]:
from sklearn.naive_bayes import GaussianNB

classifier2 = GaussianNB()

classifier2.fit(x_train,y_train)

GaussianNB()

In [15]:
y_pred2 = classifier2.predict(x_test)
print(y_pred2)

[0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 1
 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 1
 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0
 0 1 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0
 1 0 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0
 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0
 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0
 1 0 0 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 0
 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 1
 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0
 0 0 1 1 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0
 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0
 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1
 1 0 1 0 0 0 1 0 0 0 0 0 

In [16]:
cm = confusion_matrix(y_test,y_pred2)
print(cm)

accuracy_score(y_test,y_pred2)

[[355 167]
 [ 98  74]]


0.6181556195965417

In [17]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [18]:
models = [LogisticRegression(),svm.SVC(kernel='rbf'),KNeighborsClassifier(),RandomForestClassifier()]

In [19]:
def cross_val_compare():
  for model in models:
    cv_score = cross_val_score(model,x,y,cv=5)
    mean_accuracy = sum(cv_score)/len(cv_score)
    mean_accuracy = mean_accuracy*100
    mean_accuracy = round(mean_accuracy,2)

    print("Cross Validation Accuracy for the ",model,"= ",cv_score)
    print("Accuracy % for the ",model,"= ",mean_accuracy)

In [20]:
cross_val_compare()

Cross Validation Accuracy for the  LogisticRegression() =  [0.74207493 0.71902017 0.72910663 0.73304473 0.73448773]
Accuracy % for the  LogisticRegression() =  73.15
Cross Validation Accuracy for the  SVC() =  [0.74927954 0.74927954 0.75072046 0.75036075 0.75036075]
Accuracy % for the  SVC() =  75.0
Cross Validation Accuracy for the  KNeighborsClassifier() =  [0.73631124 0.73631124 0.74783862 0.74603175 0.74025974]
Accuracy % for the  KNeighborsClassifier() =  74.14
Cross Validation Accuracy for the  RandomForestClassifier() =  [0.74351585 0.72190202 0.73487032 0.75901876 0.75324675]
Accuracy % for the  RandomForestClassifier() =  74.25


In [21]:
cv_score_nb = cross_val_score(GaussianNB(),x,y,cv=5)
print(cv_score_nb)
mean_accuracy_nb = sum(cv_score_nb)/len(cv_score_nb)
mean_accuracy_nb = mean_accuracy_nb*100
mean_accuracy_nb = round(mean_accuracy_nb,2)
print(mean_accuracy_nb)

[0.52161383 0.59365994 0.57060519 0.57864358 0.59451659]
57.18


In [22]:
classifier3 = KNeighborsClassifier()

classifier3.fit(x_train,y_train)

KNeighborsClassifier()

In [23]:
y_pred3 = classifier3.predict(x_test)
print(y_pred3)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [24]:
cm = confusion_matrix(y_test,y_pred3)
print(cm)

accuracy_score(y_test,y_pred3)

[[516   6]
 [172   0]]


0.7435158501440923

In [25]:
dataset['weights'] = 1/dataset.shape[0]
dataset.head()

Unnamed: 0                                              tweet  sarcastic  \
0           0  The only thing I got from college is a caffein...          1   
1           1  I love it when professors draw a big question ...          1   
2           2  Remember the hundred emails from companies whe...          1   
3           3  Today my pop-pop told me I was not “forced” to...          1   
4           4  @VolphanCarol @littlewhitty @mysticalmanatee I...          1   

   sarcasm  irony  satire  understatement  overstatement  rhetorical_question  \
0      0.0    1.0     0.0             0.0            0.0                  0.0   
1      1.0    0.0     0.0             0.0            0.0                  0.0   
2      0.0    1.0     0.0             0.0            0.0                  0.0   
3      1.0    0.0     0.0             0.0            0.0                  0.0   
4      1.0    0.0     0.0             0.0            0.0                  0.0   

    weights  
0  0.000288  
1  0.000288  
2  0.000288  
3  0.000288  
4  0.000288

In [26]:
from sklearn.tree import DecisionTreeClassifier

classifier4 = DecisionTreeClassifier(max_depth = 1)
classifier4.fit(x,y)

DecisionTreeClassifier(max_depth=1)

In [35]:
y_pred4 = classifier.predict(x)
dataset['y_pred'] = y_pred4
dataset.head()

accuracy_score(y,y_pred4)

0.8393886966551326

In [36]:
dataset.head()

Unnamed: 0                                              tweet  sarcastic  \
0           0  The only thing I got from college is a caffein...          1   
1           1  I love it when professors draw a big question ...          1   
2           2  Remember the hundred emails from companies whe...          1   
3           3  Today my pop-pop told me I was not “forced” to...          1   
4           4  @VolphanCarol @littlewhitty @mysticalmanatee I...          1   

   sarcasm  irony  satire  understatement  overstatement  rhetorical_question  \
0      0.0    1.0     0.0             0.0            0.0                  0.0   
1      1.0    0.0     0.0             0.0            0.0                  0.0   
2      0.0    1.0     0.0             0.0            0.0                  0.0   
3      1.0    0.0     0.0             0.0            0.0                  0.0   
4      1.0    0.0     0.0             0.0            0.0                  0.0   

    weights  y_pred  
0  0.000288       0  
1  0.000288       0  
2  0.000288       1  
3  0.000288       1  
4  0.000288       0

In [31]:
def calculate_model_weight(error):
  return 0.5*np.log((1-error)/(error))

In [37]:
alpha1 = calculate_model_weight(0.161)
alpha1

0.8254031707413715

In [38]:
def update_row_weights(row,alpha = 0.825):
  if row['sarcastic'] == row['y_pred']:
    return row['weights']*np.exp(-alpha)
  else:
    return row['weights']*np.exp(alpha)


In [39]:
dataset['updated_weights'] = dataset.apply(update_row_weights,axis = 1)
dataset.head()

Unnamed: 0                                              tweet  sarcastic  \
0           0  The only thing I got from college is a caffein...          1   
1           1  I love it when professors draw a big question ...          1   
2           2  Remember the hundred emails from companies whe...          1   
3           3  Today my pop-pop told me I was not “forced” to...          1   
4           4  @VolphanCarol @littlewhitty @mysticalmanatee I...          1   

   sarcasm  irony  satire  understatement  overstatement  rhetorical_question  \
0      0.0    1.0     0.0             0.0            0.0                  0.0   
1      1.0    0.0     0.0             0.0            0.0                  0.0   
2      0.0    1.0     0.0             0.0            0.0                  0.0   
3      1.0    0.0     0.0             0.0            0.0                  0.0   
4      1.0    0.0     0.0             0.0            0.0                  0.0   

    weights  y_pred  updated_weights  
0  0.000288       0         0.000658  
1  0.000288       0         0.000658  
2  0.000288       1         0.000126  
3  0.000288       1         0.000126  
4  0.000288       0         0.000658

In [40]:
dataset['normalised_weights'] = dataset['updated_weights']/dataset['updated_weights'].sum()

In [41]:
dataset['normalised_weights'].sum()

0.9999999999999999

In [42]:
dataset['cumsum_upper'] = np.cumsum(dataset['normalised_weights'])

In [43]:
dataset['cumsum_lower'] = dataset['cumsum_upper'] - dataset['normalised_weights']

In [44]:
def create_new_dataset(dataset):
  indices = []

  for i in range(dataset.shape[0]):
    a = np.random.random()
    for index,row in dataset.iterrows():
      if a >= row['cumsum_lower'] and a <= row['cumsum_upper']:
        indices.append(index)
  return indices

In [45]:
index_values = create_new_dataset(dataset)

In [46]:
second_df = dataset.iloc[index_values,[0,1,2,9]]

In [47]:
second_df.head()

Unnamed: 0                                              tweet  \
144          144  @SuspendThePres But what were the ratings??  (...   
413          413        why is the weather having a mid life crisis   
59            59  Started watching house of cards, 4 episodes in...   
1305        1305  I'm glad I downloaded tiktok, it brings me bac...   
77            77  okay but like the say so song ain’t that bad. ...   

      sarcastic   weights  
144           1  0.000288  
413           1  0.000288  
59            1  0.000288  
1305          0  0.000288  
77            1  0.000288

In [ ]:
corpus=[]

for i in range(0,3468):
  review = re.sub('^[a-zA-Z]',' ',str(second_df['tweet'][i]))
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in all_stopwords]
  review = ' '.join(review)
  corpus.append(review)

In [59]:
cv2 = CountVectorizer()

In [60]:
X = cv2.fit_transform(corpus).toarray()
Y = second_df.iloc[:,2].values

In [61]:
dt2 = DecisionTreeClassifier(max_depth = 1)
dt2.fit(X,Y)

DecisionTreeClassifier(max_depth=1)

In [62]:
y_pred5 = dt2.predict(X)
second_df['y_pred'] = y_pred5
second_df.head()

accuracy_score(Y,y_pred5)

0.5573817762399077