In [ ]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('/content/Sarcasm Dataset.csv')

In [ ]:
dataset.head()

Unnamed: 0                                              tweet  sarcastic  \
0           0  The only thing I got from college is a caffein...          1   
1           1  I love it when professors draw a big question ...          1   
2           2  Remember the hundred emails from companies whe...          1   
3           3  Today my pop-pop told me I was not “forced” to...          1   
4           4  @VolphanCarol @littlewhitty @mysticalmanatee I...          1   

   sarcasm  irony  satire  understatement  overstatement  rhetorical_question  
0      0.0    1.0     0.0             0.0            0.0                  0.0  
1      1.0    0.0     0.0             0.0            0.0                  0.0  
2      0.0    1.0     0.0             0.0            0.0                  0.0  
3      1.0    0.0     0.0             0.0            0.0                  0.0  
4      1.0    0.0     0.0             0.0            0.0                  0.0

In [ ]:
dataset.shape

(3468, 9)

In [ ]:
import re
import nltk

nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

all_stopwords = stopwords.words('english')
all_stopwords.remove('not')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
corpus=[]

for i in range(0,3468):
  review = re.sub('^[a-zA-Z]',' ',str(dataset['tweet'][i]))
  review = review.lower()
  review = review.split()
  review = [ps.stem(word) for word in review if not word in all_stopwords]
  review = ' '.join(review)
  corpus.append(review)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()


In [ ]:
x = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:,2].values

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 2)

In [ ]:
from sklearn import svm

classifier = svm.SVC(kernel = 'rbf')
classifier.fit(x_train,y_train)

SVC()

In [ ]:
y_pred = classifier.predict(x_test)

print(y_pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm = confusion_matrix(y_test,y_pred)
print(cm)

accuracy_score(y_test,y_pred)

[[522   0]
 [171   1]]


0.7536023054755043

In [ ]:
from sklearn.naive_bayes import GaussianNB

classifier2 = GaussianNB()

classifier2.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred2 = classifier2.predict(x_test)
print(y_pred2)

[0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 1
 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 1
 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0
 0 1 0 0 0 0 0 1 1 0 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 1 0
 1 0 0 0 0 1 0 0 0 1 1 0 1 1 0 1 1 0 1 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 0 0 0
 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0
 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0
 1 0 0 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 0
 0 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 1 0 1 1
 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 0 0 1 1 0 1 0 0 1 0
 0 0 1 1 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 0
 1 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 1 1 0 0 1 0 0
 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1
 1 0 1 0 0 0 1 0 0 0 0 0 

In [ ]:
cm = confusion_matrix(y_test,y_pred2)
print(cm)

accuracy_score(y_test,y_pred2)

[[355 167]
 [ 98  74]]


0.6181556195965417

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [ ]:
models = [LogisticRegression(),svm.SVC(kernel='rbf'),KNeighborsClassifier(),RandomForestClassifier()]

In [ ]:
def cross_val_compare():
  for model in models:
    cv_score = cross_val_score(model,x,y,cv=5)
    mean_accuracy = sum(cv_score)/len(cv_score)
    mean_accuracy = mean_accuracy*100
    mean_accuracy = round(mean_accuracy,2)

    print("Cross Validation Accuracy for the ",model,"= ",cv_score)
    print("Accuracy % for the ",model,"= ",mean_accuracy)

In [ ]:
cross_val_compare()

Cross Validation Accuracy for the  LogisticRegression() =  [0.74207493 0.71902017 0.72910663 0.73304473 0.73448773]
Accuracy % for the  LogisticRegression() =  73.15
Cross Validation Accuracy for the  SVC() =  [0.74927954 0.74927954 0.75072046 0.75036075 0.75036075]
Accuracy % for the  SVC() =  75.0
Cross Validation Accuracy for the  KNeighborsClassifier() =  [0.73631124 0.73631124 0.74783862 0.74603175 0.74025974]
Accuracy % for the  KNeighborsClassifier() =  74.14
Cross Validation Accuracy for the  RandomForestClassifier() =  [0.74351585 0.72190202 0.73487032 0.75901876 0.75324675]
Accuracy % for the  RandomForestClassifier() =  74.25


In [ ]:
cv_score_nb = cross_val_score(GaussianNB(),x,y,cv=5)
print(cv_score_nb)
mean_accuracy_nb = sum(cv_score_nb)/len(cv_score_nb)
mean_accuracy_nb = mean_accuracy_nb*100
mean_accuracy_nb = round(mean_accuracy_nb,2)
print(mean_accuracy_nb)

[0.52161383 0.59365994 0.57060519 0.57864358 0.59451659]
57.18


In [ ]:
classifier3 = KNeighborsClassifier()

classifier3.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred3 = classifier3.predict(x_test)
print(y_pred3)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [ ]:
cm = confusion_matrix(y_test,y_pred3)
print(cm)

accuracy_score(y_test,y_pred3)

[[516   6]
 [172   0]]


0.7435158501440923

In [ ]:
dataset['weights'] = 1/dataset.shape[0]
dataset.head()

Unnamed: 0                                              tweet  sarcastic  \
0           0  The only thing I got from college is a caffein...          1   
1           1  I love it when professors draw a big question ...          1   
2           2  Remember the hundred emails from companies whe...          1   
3           3  Today my pop-pop told me I was not “forced” to...          1   
4           4  @VolphanCarol @littlewhitty @mysticalmanatee I...          1   

   sarcasm  irony  satire  understatement  overstatement  rhetorical_question  \
0      0.0    1.0     0.0             0.0            0.0                  0.0   
1      1.0    0.0     0.0             0.0            0.0                  0.0   
2      0.0    1.0     0.0             0.0            0.0                  0.0   
3      1.0    0.0     0.0             0.0            0.0                  0.0   
4      1.0    0.0     0.0             0.0            0.0                  0.0   

    weights  
0  0.000288  
1  0.000288  
2  0.000288  
3  0.000288  
4  0.000288